version: '3.4'
services:
  cafeteria-enduser:
    build:
      context: ./cafeteria-enduser
      dockerfile: Dockerfile
    container_name: cafeteria-enduser
    environment:
      NGINX_PORT: 8000
    ports:
      - "8000:8000"
  cafeteria-backend:
    container_name: cafeteria-backend
    build:
      context: ./cafeteria-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  cafeteria-db:
    image: postgres:14.2-alpine
    container_name: cafeteria-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cafeteria
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: dummy
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
    - ./cafeteria-backend/docker/db:/docker-entrypoint-initdb.d
    - cafeteria-db-data:/var/lib/postgresql/data
volumes:
  cafeteria-db-data: