import { Meal } from './meal';

export const MEALS: Meal[] = [
  {
    id: '1',
    name: 'Kuřecí řízek',
    nameEng: 'Schnitzel',
    cost: '120 CZK',
    date: '12.11.2021',
    alergens: ['1', '3', '4'],
  },
  {
    id: '2',
    name: 'Vepřové kostky na hříbkách s knedlíkem',
    nameEng: 'Pork cubes on porcini mushrooms with dumplings',
    cost: '99 CZK',
    date: '12.11.2021',
  },
  {
    id: '3',
    name: 'Cikánský guláš s knedlíkem',
    nameEng: 'Gypsy stew with dumplings',
    cost: '110 CZK',
    date: '12.11.2021',
  },
  {
    id: '4',
    name: 'Vepřová po selsku bramborový knedlík špenát',
    nameEng: 'Pork potato dumpling spinach',
    cost: '105 CZK',
    date: '13.11.2021',
  },
  {
    id: '5',
    name: 'Smažený sýr hranolky tatarská omáčka',
    nameEng: 'Fried cheese fries tartar sauce',
    cost: '100 CZK',
    date: '13.11.2021',
  },
  {
    id: '6',
    name: 'Kuřecí plátek šťouchané brambory',
    nameEng: 'Chicken slice with mashed potatoes',
    cost: '115 CZK',
    date: '13.11.2021',
  },
  {
    id: '7',
    name: 'Koprová omáčka s vejci a hovězím masem knedlík ',
    nameEng: 'Dill sauce with eggs and beef dumpling',
    cost: '130 CZK',
    date: '14.11.2021',
  },
  {
    id: '8',
    name: 'Vepřové výpečky bramborový knedlík červené zelí ',
    nameEng: 'Pork pastry potato dumpling red cabbage',
    cost: '120 CZK',
    date: '14.11.2021',
  },
  {
    id: '9',
    name: 'Indické kuřecí maso s rýží ',
    nameEng: 'Indian chicken with rice',
    cost: '105 CZK',
    date: '14.11.2021',
  },
  {
    id: '10',
    name: 'Smažený hermelín brambory tatarská omáčka ',
    nameEng: 'Fried Camembert Potato Tartar Sauce',
    cost: '115 CZK',
    date: '15.11.2021',
  },
  {
    id: '11',
    name: 'Kovbojské fazole s klobásou a okurkou,chléb ',
    nameEng: 'Cowboy beans with sausage and cucumber, bread',
    cost: '99 CZK',
    date: '15.11.2021',
  },
  {
    id: '12',
    name: 'Plněné bramborové knedlíky uzeninou zelí ',
    nameEng: 'Stuffed potato dumplings with cabbage sausage',
    cost: '135 CZK',
    date: '15.11.2021',
  },
  {
    id: '13',
    name: 'Drůbeží rizoto se sýrem ',
    nameEng: 'Poultry risotto with cheese',
    cost: '100 CZK',
    date: '16.11.2021',
  },
  {
    id: '14',
    name: 'Vepřový steak se smetanovým pórkem na slanině hranolky ',
    nameEng: 'Pork steak with creamy leek on bacon fries',
    cost: '150 CZK',
    date: '16.11.2021',
  },
  {
    id: '15',
    name: 'Pizza',
    nameEng: 'Pizza',
    cost: '145 CZK',
    date: '16.11.2021',
  },
  {
    id: '16',
    name: 'Přírodní sekaný karbanátek,rajčatová salsa,vařené brambory ',
    nameEng: 'Natural chopped meatball, tomato salsa, boiled potatoes',
    cost: '105 CZK',
    date: '17.11.2021',
  },
  {
    id: '17',
    name: 'Boloňské lasagne se sýrem a mletým masem ',
    nameEng: 'Lasagna bolognese with cheese and minced meat',
    cost: '100 CZK',
    date: '17.11.2021',
  },
  {
    id: '18',
    name: 'XXL Smažený řízek bramborová kaše okurka',
    nameEng: 'XXL Fried schnitzel mashed cucumber',
    cost: '160 CZK',
    date: '17.11.2021',
  },
  {
    id: '19',
    name: 'Kuřecí plátek šťouchané brambory',
    nameEng: 'Chicken slice with mashed potatoes',
    cost: '115 CZK',
    date: '18.11.2021',
  },
  {
    id: '20',
    name: 'Krůtí nudličky se zeleninou a rýží ',
    nameEng: 'Turkey strips with vegetables and rice',
    cost: '110 CZK',
    date: '18.11.2021',
  },
  {
    id: '21',
    name: 'Alpské borůvkové knedlíky s vanilkovým krémem sypané mákem',
    nameEng: 'Alpine blueberry dumplings with vanilla cream sprinkled with poppy seeds',
    cost: '115 CZK',
    date: '18.11.2021',
  },
];
